# opensearch needs sysctl -w vm.max_map_count=262144
# see https://stackoverflow.com/questions/66444027/max-virtual-memory-areas-vm-max-map-count-65530-is-too-low-increase-to-at-lea
version: '3'
services:

  ingest:
    image: ghcr.io/collective/collective.elastic.ingest:latest
    volumes:
      - ingest-configuration:/configuration
    networks:
      - default
      - opensearch-net

  redis:
    image: 'redis:latest'
    networks:
      - backend
    ports:
      - 6379:6379

  opensearch:
    image: opensearch-ingest-attachment:latest # Specifying the freshly build local image
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    networks:
      - opensearch-net

volumes:
  opensearch-data:
  ingest-configuration:
    driver_opts:
      type: none
      device: ./configuration
      o: bind
networks:
  opensearch-net:
  default:
    external: true
    name: container_network

